capitalization correction for Counter title (#206)
* Update collections.rst

* parallel sorting bug fix

Python 3 zip object no longer supports .sort()
AttributeError: 'zip' object has no attribute 'sort'

Changed to sorted to be forward compatible